# Generated by Django 6.0.2 on 2026-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', '---'), ('EasyPaisa', 'EasyPaisa'), ('JazzCash', 'JazzCash'), ('Bank', 'Bank Transfer')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Used', 'Used')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='pinrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
