# Generated by Django 6.0.2 on 2026-02-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_deposit_payment_method_alter_deposit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='screenshot',
            field=models.TextField(blank=True, default='', help_text='Base64 screenshot of payment proof'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='sender_account',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
