# Generated by Django 6.0.2 on 2026-02-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deposit_screenshot_deposit_sender_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('EasyPaisa', 'EasyPaisa'), ('JazzCash', 'JazzCash'), ('Bank', 'Bank Transfer')], default='', max_length=50),
        ),
    ]
